name: Build Linux Release

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:

  build-linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-cache
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install LinuxDeploy
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: qt appimage

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libharfbuzz-dev \
            libxrandr-dev \
            libxi-dev \
            libglu1-mesa-dev \
            fuse \
            libxcb-cursor0 \
            libspeechd2

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.2'
          modules: 'all'
          cache: true

      - name: Build
        run: MAKE_PARALLEL=$(nproc) ./linuxdeploy_build_and_release.sh
        env:
          CC: gcc-11
          CXX: g++-11

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sioyek-linux
          path: sioyek-release-linux.zip

  upload-release:
    if: ${{ github.event_name != 'pull_request' }}
    needs: build-linux
    runs-on: ubuntu-22.04

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: sioyek-linux

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: sioyek-release-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
